# Generated by Django 4.1.6 on 2023-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_caidalibre_distancia_remove_caidalibre_tiempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caidalibre',
            name='inp',
        ),
        migrations.RemoveField(
            model_name='caidalibre',
            name='ou',
        ),
        migrations.AddField(
            model_name='caidalibre',
            name='distancia',
            field=models.IntegerField(null=True, verbose_name='distancia'),
        ),
        migrations.AddField(
            model_name='caidalibre',
            name='tiempo',
            field=models.FloatField(null=True, verbose_name='tiempo'),
        ),
        migrations.AddField(
            model_name='caidalibre',
            name='velocidad',
            field=models.FloatField(null=True, verbose_name='velocidad'),
        ),
    ]
