version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: '12345'
    ports:
      - '8000:8000'
    networks:
      - mynet

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/proyecto
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: '12345'
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - mynet

networks:
  mynet:
